AMIAQuestioning/AMIAQuestioning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('questioning/', include('questioning.urls')),
    path('course/', include('course.urls')),
    path('graduate/', include('graduate.urls')),
    path('big_test/', include('big_test.urls')),
    path('adaptation/', include('adaptation.urls')),
    path('beka/', include('beka_scale.urls')),
    path('personal-work/', include('personalwork.urls')),
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
    # path('', RedirectView.as_view(url='/questioning'), name='index'),
    # path('results/', TemplateView.as_view(template_name="index.html"), name='results'),
    path('accounts/', include('django.contrib.auth.urls'))
]

AMIAQuestioning/big_test/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'testing'

urlpatterns = [
    path('', views.test_form_add, name='test_add'),
    path('dashboard', login_required(views.dashboard), name='test_dashboard'),
    path('success', views.success, name='test_success'),
]

AMIAQuestioning/course/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'course'

urlpatterns = [
    path('', views.questioning_add, name='add'),
    path('success/', views.success, name='success'),
    path('dashboard/', login_required(views.dashboard), name='dashboard'),
]

AMIAQuestioning/big_test/models.py
from django.db import models
from course.models import Group


class TestKind(models.Model):
    kind = models.CharField(max_length=255, verbose_name="Вид теста")

    def __str__(self):
        return self.kind

    class Meta:
        ordering = ('kind',)
        verbose_name = 'Вид теста'
        verbose_name_plural = 'Виды тестов'


class Question(models.Model):
    question_number = models.IntegerField(verbose_name='Номер вопроса', blank=True, null=True)
    question_text = models.CharField(max_length=255, verbose_name='Вопрос')

    def __str__(self):
        return 'Номер вопроса ' + str(self.question_number) + ' Тест вопроса - ' + self.question_text

    class Meta:
        ordering = ('id',)
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'


class Questionary(models.Model):
    fio = models.CharField(max_length=255, verbose_name='Фамилия')
    # group = models.CharField(max_length=255, verbose_name='Группа')
    group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='Группа')
    kind = models.ForeignKey(TestKind, on_delete=models.SET_NULL, verbose_name="Вид теста", blank=True, null=True)
    date_of_birth = models.CharField(max_length=255, verbose_name='Дата рождения', blank=True, null=True)
    date_of_fill = models.DateField(verbose_name="Дата заполнения", auto_now_add=True)
    timer = models.IntegerField(verbose_name="Таймер", blank=True, null=True)

    def __str__(self):
        return self.fio + ' ' + str(self.date_of_fill)

    class Meta:
        ordering = ('id',)
        verbose_name = 'Анкета'
        verbose_name_plural = 'Анкеты'


class Result(models.Model):
    questionary = models.ForeignKey(Questionary, on_delete=models.CASCADE, verbose_name="Анкета")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name="Вопрос")
    answer = models.IntegerField(verbose_name="Ответ")

    def __str__(self):
        return self.questionary.fio + ' ' + self.question.question_text + ' ' + str(self.answer)

    class Meta:
        ordering = ('id',)
        verbose_name = 'Результат'
        verbose_name_plural = 'Результаты'

AMIAQuestioning/big_test/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .models import Question, Questionary, Result, TestKind
from django.urls import reverse
from django.views.decorators.cache import cache_page
from course.models import Group


def test_form_add(request):
    if request.method == 'POST':
        questionary_new = Questionary(
            fio=request.POST['fio'],
            group=get_object_or_404(Group, pk=request.POST['group']),
            kind=get_object_or_404(TestKind, pk=1),
            date_of_birth=request.POST.get('date_of_birth'),
            timer=request.POST.get('timer', 0)
        )
        questionary_new.save()
        for question_loop in Question.objects.all():
            result = Result(
                questionary=questionary_new,
                question=question_loop,
                answer=request.POST['question_' + str(question_loop.id) + '_radio']
            )
            result.save()
        return HttpResponseRedirect(reverse('testing:test_success'))
    else:
        question_list = Question.objects.all()
        group_list = Group.objects.all()
        return render(request, 'testing/test_input_form.html',
                      {'question_list': question_list,
                       'group_list': group_list,
                       })


def dashboard(request):
    result_list = Result.objects.all().order_by('questionary__fio')
    question_list = Question.objects.all()
    questionary_list = Questionary.objects.all()

    return render(request, 'testing/dashboard.html', {
        'result_list': result_list,
        'question_list': question_list,
        'questionary_list': questionary_list,
    })


def success(request):
    return render(request, 'testing/success.html')

AMIAQuestioning/big_test/templates/testing/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load filter_tags_big %}

{% block title %}<title>Результаты</title>{% endblock %}

{% block nav %}{% include 'course/nav.html' %}{% endblock %}

{% block content %}

    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">№ п/п</th>
            <th scope="col">ФИО</th>
            <th scope="col">Группа</th>
            <th scope="col">Дата рождения</th>
            <th scope="col">Дата заполнения</th>
            {% for question in question_list %}
                <th scope="col">{{ question.question_number }}</th>
            {% endfor %}
            <th scope="col">Время прохождения теста (сек.)</th>
        </tr>
        </thead>
        <tbody>
        {% for questionary in questionary_list %}
            <tr>
                <th scope="col">{{ forloop.counter }}</th>
                <th scope="col">{{ questionary.fio }}</th>
                <th scope="col">{{ questionary.group }}</th>
                <th scope="col"><nobr>{{ questionary.date_of_birth }}</nobr></th>
                <th scope="col">{{ questionary.date_of_fill|date:'Y-m-d' }}</th>
                {% for result in result_list|results_big:questionary.id %}
                    <th scope="col">{{ result.answer }}</th>
                {% endfor %}
                <th scope="col">{{ questionary.timer }}</th>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

AMIAQuestioning/big_test/templates/testing/success.html
{% extends 'base.html' %}
{% load static %}
{% load filter_tags_big %}

{% block title %}<title>Анкета</title>{% endblock %}

{% block nav %}{% include 'course/nav.html' %}{% endblock %}

{% block content %}
    <div class="container-fluid">
        <br>
        <div class="card" style="width: 100%;">
            <div class="card-body">
                <h5 class="card-title">Вы успешно выполнили задание!</h5>
                <p class="card-text">Благодарим за участие!</p>
                <p class="card-text">Ожидайте окончания выполнения задания другими курсантами!</p>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        setTimeout(()=> window.location.href = 'https://www.amia.by/senior-management', 3000);
    </script>
{% endblock %}

AMIAQuestioning/big_test/templates/testing/test_input_form.html
<!doctype html>
<html lang="ru">
<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'main/css/bs5/bootstrap.min.css' %}">
    {#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">#}
    <link rel="shortcut icon" href="{% static 'questioning/img/favicon.ico' %}"/>
    <title>Анкета</title>
</head>
<body>

<div class="container-fluid">
    {% include 'course/nav.html' %}
</div>

<div class="container">
    <h4>
        <div class="fixed-bottom m-2 badge bg-dark" id="user_timer" style="width: 100px;"></div>
    </h4>
    <br>
    <h5 class="d-flex justify-content-center">Тест оценки психологической устойчивости</h5><br>
    <p class="card-text" align="justify">
        ИНСТРУКЦИЯ. Прохождение теста займет у Вас приблизительно 10 минут.
        Убедитесь, что правильно поняли утверждение и выберите вариант ответа, который в большей степени соответствует
        вашему мнению и представлению о себе.
        Здесь нет «правильных» или «неправильных» ответов, поэтому не задерживайтесь слишком долго на одном вопросе.
        Старайтесь как можно реже прибегать к ответу «Затрудняюсь ответить». Тест-опросник считается выполненным при
        наличии ответа на каждое из предложенных утверждений.
    </p>

    <p><b>Тест-опросник считается выполненным при наличии ответа на каждое из предложенных утверждений. Перепроверьте
        себя на наличие пропущенных ответов.</b></p>
    <br>
    <form action="{% url 'testing:test_add' %}" method="POST" class="needs-validation" id="test_form"
          novalidate>{% csrf_token %}
        <input type="hidden" name="timer" id="id_timer">
        <div class="row">
            <div class="col-sm-6">
                <div class="mb-3">
                    <label class="form-label">Ф.И.О</label>
                    <input type="text" class="form-control shadow-lg bg-white rounded" name="fio" id="id_fio"
                           placeholder="Например: Иванов Иван Иванович" required>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="mb-3">
                    <label class="form-label">Группа</label>
                    <select class="form-select shadow-lg bg-white rounded" name="group" required>
                        {% for group in group_list %}
                            <option value="{{ group.id }}">{{ group.group_number }}</option>
                        {% endfor %}
                    </select>
                    {#                    <input type="text" class="form-control shadow-lg bg-white rounded" name="group" required>#}
                </div>
            </div>
            <div class="col-sm-3">
                <div class="mb-3">
                    <label class="form-label">Дата рождения</label>
                    <input type="date" class="form-control shadow-lg bg-white rounded" name="date_of_birth" required>
                </div>
            </div>
        </div>

        {% for question in question_list %}
            <div class="card shadow-lg bg-white rounded" style="width: 100%;">
                <div class="card-body">
                    <h5 class="card-title">{{ question.question_text }}</h5>
                    <p class="card-text">
                    <div class="form-check">
                        <input class="form-check-input mx-2" type="radio" name="question_{{ question.id }}_radio"
                               value="1" required>
                        <label class="form-check-label">Полностью не согласен (это ко мне совершенно не
                            относится)</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input mx-2" type="radio" name="question_{{ question.id }}_radio"
                               value="2" required>
                        <label class="form-check-label">Не согласен (мне это не свойственно в большинстве
                            случаев)</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input mx-2" type="radio" name="question_{{ question.id }}_radio"
                               value="3" required>
                        <label class="form-check-label">Затрудняюсь ответить (не могу решить, верно это утверждение или
                            нет)</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input mx-2" type="radio" name="question_{{ question.id }}_radio"
                               value="4" required>
                        <label class="form-check-label">Согласен (это на меня похоже)</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input mx-2" type="radio" name="question_{{ question.id }}_radio"
                               value="5" required>
                        <label class="form-check-label">Полностью согласен (это точно про меня)</label>
                    </div>
                    </p>
                </div>
            </div>
            <br>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>

</div>

{#<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>#}
<script src="{% static 'main/js/JQueryLocal.js' %}"></script>
<script src="{% static 'main/js/bs5/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'big_test/js/main.js' %}"></script>
<script src="{% static 'adaptation/js/timer.js' %}"></script>
<script>(function () {
    'use strict'

    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.querySelectorAll('.needs-validation')

    // Loop over them and prevent submission
    Array.prototype.slice.call(forms)
        .forEach(function (form) {
            form.addEventListener('submit', function (event) {
                if (!form.checkValidity()) {
                    event.preventDefault()
                    event.stopPropagation()

                }

                form.classList.add('was-validated')
            }, false)
        })
})()
</script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
-->
</body>
</html>