AMIAQuestioning/AMIAQuestioning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('questioning/', include('questioning.urls')),
    path('course/', include('course.urls')),
    path('graduate/', include('graduate.urls')),
    path('big_test/', include('big_test.urls')),
    path('adaptation/', include('adaptation.urls')),
    path('beka/', include('beka_scale.urls')),
    path('personal-work/', include('personalwork.urls')),
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
    # path('', RedirectView.as_view(url='/questioning'), name='index'),
    # path('results/', TemplateView.as_view(template_name="index.html"), name='results'),
    path('accounts/', include('django.contrib.auth.urls'))
]

AMIAQuestioning/course/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'course'

urlpatterns = [
    path('', views.questioning_add, name='add'),
    path('success/', views.success, name='success'),
    path('dashboard/', login_required(views.dashboard), name='dashboard'),
]

AMIAQuestioning/personalwork/urls.py
from django.urls import path
from . import views


app_name = 'personalwork'

urlpatterns = [
    path('', views.work_list, name='work_list'),
    path('add', views.work_input, name='work_input'),
    path('<work_id>/update', views.work_update, name='work_update'),
    # path('subdivisions', views.get_subdivisions, name='work_update'),
]

AMIAQuestioning/course/models.py
from django.db import models

no_yes_list = ['', 'нет', 'да']
yes_no_list = ['', 'да', 'нет']


# class TestKind(models.Model):
#     kind = models.CharField(max_length=255, verbose_name="Вид теста")
#
#     def __str__(self):
#         return self.kind
#
#     class Meta:
#         ordering = ('kind',)
#         verbose_name = 'Вид теста'
#         verbose_name_plural = 'Виды тестов'


class Group(models.Model):
    group_number = models.CharField(max_length=255, verbose_name='Номер группы')

    def __str__(self):
        return self.group_number

    class Meta:
        ordering = ('group_number',)
        verbose_name = 'Группа курсантов'
        verbose_name_plural = 'Группы курсантов'


class Interest(models.Model):
    interest_name = models.CharField(max_length=255, verbose_name='Интерес')

    def __str__(self):
        return self.interest_name

    class Meta:
        ordering = ('id',)
        verbose_name = 'Интерес'
        verbose_name_plural = 'Интересы'


class ParticipationInEducation(models.Model):
    participation = models.CharField(max_length=255, verbose_name='В дошкольном возрасте в '
                                                                  'вашем воспитании преимущественно принимали участие')

    def __str__(self):
        return self.participation

    class Meta:
        ordering = ('id',)
        verbose_name = 'В дошкольном возрасте в вашем воспитании преимущественно принимали участие'
        verbose_name_plural = 'В дошкольном возрасте в вашем воспитании преимущественно принимали участие'


class Relationship(models.Model):
    relationship = models.CharField(max_length=255, verbose_name='Отношение')

    def __str__(self):
        return self.relationship

    class Meta:
        ordering = ('id',)
        verbose_name = 'Отношение'
        verbose_name_plural = 'Отношения'


class ParticularQualities(models.Model):
    particular_qualities = models.CharField(max_length=255, verbose_name='Особенность')

    def __str__(self):
        return self.particular_qualities

    class Meta:
        ordering = ('id',)
        verbose_name = 'Особенность'
        verbose_name_plural = 'Особенности'


class RelativesRecord(models.Model):
    record = models.CharField(max_length=255, verbose_name='Учет у врача')

    def __str__(self):
        return self.record

    class Meta:
        ordering = ('id',)
        verbose_name = 'Учет у врача'
        verbose_name_plural = 'Учет у врача'


class Activity(models.Model):
    activity = models.CharField(max_length=255, verbose_name='Деятельность')

    def __str__(self):
        return self.activity

    class Meta:
        ordering = ('id',)
        verbose_name = 'Деятельность'
        verbose_name_plural = 'Деятельности'


class Ability(models.Model):
    ability = models.CharField(max_length=255, verbose_name='Способность')

    def __str__(self):
        return self.ability

    class Meta:
        ordering = ('id',)
        verbose_name = 'Способность'
        verbose_name_plural = 'Способности'


class Messenger(models.Model):
    messenger = models.CharField(max_length=255, verbose_name='Messenger')

    def __str__(self):
        return self.messenger

    class Meta:
        ordering = ('messenger',)
        verbose_name = 'Messenger'
        verbose_name_plural = 'Messengers'


class Guardian(models.Model):
    guardian = models.CharField(max_length=255, verbose_name='Опекун')

    def __str__(self):
        return self.guardian

    class Meta:
        ordering = ('id',)
        verbose_name = 'Опекун'
        verbose_name_plural = 'Опекуны'


class MotherFather(models.Model):
    parent = models.CharField(max_length=255, verbose_name='Родитель (родные)')

    def __str__(self):
        return self.parent

    class Meta:
        ordering = ('id',)
        verbose_name = 'Родитель (родные)'
        verbose_name_plural = 'Родители (родные)'


class StepmotherStepfather(models.Model):
    step_parent = models.CharField(max_length=255, verbose_name='Родитель')

    def __str__(self):
        return self.step_parent

    class Meta:
        ordering = ('id',)
        verbose_name = 'Родитель'
        verbose_name_plural = 'Родители'


class Anketa(models.Model):
    group = models.ForeignKey(Group, verbose_name="Группа", null=True, on_delete=models.SET_NULL)
    # kind = models.ForeignKey(TestKind, on_delete=models.SET_NULL, verbose_name="Вид теста", blank=True, null=True)
    fio = models.CharField(max_length=255, verbose_name='ФИО')
    index_number = models.CharField(max_length=255, verbose_name='Порядковый номер')
    nationality = models.CharField(max_length=255, verbose_name='Национальность')
    religion = models.CharField(max_length=255, verbose_name='Вероисповедание')
    date_of_birth = models.DateField(verbose_name='Дата рождения')
    birth_place = models.TextField(verbose_name='Место рождения')
    education = models.IntegerField(verbose_name='Образование')
    year_of_graduation = models.IntegerField(verbose_name='Год окончания', blank=True, null=True)
    specialty = models.TextField(verbose_name='Специальность', blank=True, null=True)
    military = models.IntegerField(verbose_name='Служба в вооруженных силах')
    military_year_since = models.IntegerField(verbose_name='Служба в ВС с:', blank=True, null=True)
    military_year_till = models.IntegerField(verbose_name='Служба в ВС по:', blank=True, null=True)
    military_place = models.TextField(verbose_name='Место службы', blank=True, null=True)
    type_of_army = models.TextField(verbose_name='Род войск', blank=True, null=True)
    family_status = models.IntegerField(verbose_name='Семейное положение', default=1)
    marriage = models.IntegerField(verbose_name='Ранее в браке')
    marriage_year_since = models.IntegerField(verbose_name='Состоял в браке с:', blank=True, null=True)
    marriage_year_till = models.IntegerField(verbose_name='Состоял в браке по:', blank=True, null=True)
    children = models.IntegerField(verbose_name='Имеются ли у Вас дети', default=1)
    children_info = models.CharField(max_length=255, verbose_name='Пол и год рождения', blank=True, null=True)
    participation_in_education = models.ManyToManyField(ParticipationInEducation,
                                                        verbose_name='В дошкольном возрасте в вашем воспитании '
                                                                     'преимущественно принимали участие (подчеркните)')
    participation_in_education_other = models.CharField(max_length=255,
                                                        verbose_name='В дошкольном возрасте в вашем воспитании'
                                                                     ' преимущественно принимали участие (иное)', blank=True, null=True)
    parents = models.IntegerField(verbose_name='Родители на момент поступления в Академия МВД:')
    parents_in_marriage_live = models.IntegerField(verbose_name='Родители в браке проживают:', blank=True, null=True)
    parents_not_in_marriage_live = models.IntegerField(verbose_name='Родители не в браке проживают:', blank=True, null=True)
    parents_not_in_marriage_since = models.IntegerField(verbose_name='Родители не в браке проживают с:', blank=True, null=True)
    mother_only_father_died_year = models.IntegerField(verbose_name='Отец умер погиб (умер) в:', blank=True, null=True)
    mother_only_other = models.TextField(verbose_name='Только мать (иное)', blank=True, null=True)
    father_only_mother_died_year = models.IntegerField(verbose_name='Мать умерла погибла (умерла) в:', blank=True, null=True)
    father_only_other = models.TextField(verbose_name='Только отец (иное)', blank=True, null=True)
    mother_father = models.ForeignKey(MotherFather, verbose_name="Мать Отец", on_delete=models.SET_NULL, blank=True, null=True)
    stepmother_stepfather = models.ForeignKey(StepmotherStepfather, verbose_name="Мачеха Отчим", on_delete=models.SET_NULL, blank=True, null=True)
    guardian = models.ManyToManyField(Guardian, verbose_name='Опекуны', blank=True)
    guardian_other = models.CharField(max_length=255, verbose_name='Опекуны (иное)', blank=True, null=True)
    relationship = models.ManyToManyField(Relationship, verbose_name='Какие взаимоотношения преобладают между вашими родителями, лицами их заменяющими)')
    relationship_other = models.TextField(verbose_name='Взаимоотношения между родителями (иное)', blank=True, null=True)
    siblings = models.TextField(verbose_name='Братья и сестры', blank=True, null=True)
    interest = models.ManyToManyField(Interest, verbose_name='Ваши интересы, увлечения, хобби')
    interest_other = models.TextField(verbose_name='Ваши интересы (иное)', blank=True, null=True)
    kind_of_sport = models.CharField(max_length=255, verbose_name='Вид спорта', blank=True, null=True)
    sport_level = models.IntegerField(verbose_name='Уровень спорта', blank=True, null=True)
    periodicity = models.IntegerField(verbose_name='Периодичность', blank=True, null=True, default=1)
    achievements = models.TextField(verbose_name='Достижения', blank=True, null=True)
    not_prof = models.BooleanField(verbose_name='На постоянной основе спортом не занимался')

    is_chronic_diseases = models.IntegerField(verbose_name='Имеются ли хронические заболевания', default=1)
    chronic_diseases = models.TextField(verbose_name='Хронические заболевания', blank=True, null=True)
    is_injury = models.IntegerField(verbose_name='Были ли у Вас травмы, ранения, переломы и т.д.', default=1)
    injury = models.TextField(verbose_name='Травмы, ранения, переломы и т.д.', blank=True, null=True)
    particular_qualities = models.ManyToManyField(ParticularQualities, verbose_name='Отметьте свои особенности, которых вы стесняетесь, которые вас беспокоят')
    particular_qualities_other = models.TextField(verbose_name='Особенности (иные)', blank=True, null=True)

AMIAQuestioning/course/views.py
from django.shortcuts import render
from .forms import AnketaForm
from .models import *
from django.http import HttpResponseRedirect

from django.urls import reverse
from .filters import CourseFilter
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404


def questioning_add(request):
    if request.method == 'POST':
        form = AnketaForm(request.POST)
        if form.is_valid():
            anketa = form.save(commit=False)
            anketa.education = request.POST.get('education')
            anketa.military = request.POST.get('military')
            anketa.marriage = request.POST.get('marriage')
            anketa.parents = request.POST.get('parents')
            anketa.parents_in_marriage_live = request.POST.get('parents_in_marriage_live')
            anketa.parents_not_in_marriage_live = request.POST.get('parents_not_in_marriage_live')
            if 'mother_father1' in request.POST:
                anketa.mother_father = get_object_or_404(MotherFather, pk=request.POST.get('mother_father1'))
            if 'mother_father2' in request.POST:
                anketa.mother_father = get_object_or_404(MotherFather, pk=request.POST.get('mother_father2'))
            if 'stepmother_stepfather1' in request.POST:
                anketa.stepmother_stepfather = get_object_or_404(StepmotherStepfather, pk=request.POST.get('stepmother_stepfather1'))
            if 'stepmother_stepfather2' in request.POST:
                anketa.stepmother_stepfather = get_object_or_404(StepmotherStepfather, pk=request.POST.get('stepmother_stepfather2'))
            anketa.sport_level = request.POST.get('sport_level')
            anketa.gaming = request.POST.get('gaming')
            anketa.smoking = request.POST.get('smoking')

            anketa.save()

            form.save_m2m()

            return HttpResponseRedirect(reverse('course:success'))
        else:
            return render(request, 'course/input_form.html', {'form': form})
    else:
        form = AnketaForm
        return render(request, 'course/input_form.html', {'form': form,
                                                          })


def dashboard(request):
    f = CourseFilter(request.GET, queryset=Anketa.objects.all())
    paginator = Paginator(f.qs, 1000)
    page = request.GET.get('page')
    subjects = paginator.get_page(page)
    return render(request, 'course/dashboard.html', {'list': subjects,
                                                     'filter': f,
                                                     })


def success(request):
    return render(request, 'course/success.html')

AMIAQuestioning/course/templates/course/dashboard.html
{% extends "base.html" %}

{% block title %}
    <title>DashBoard</title>
    {% load widget_tweaks %}
    {% load static %}
    <style type="text/css">
        ul {
            list-style-type: none;
        }
        {#tr, td, th {#}
        {#    text-align: center;#}
        {#}#}
    </style>
{% endblock %}

{% block nav %}
    <div class="container-fluid">
        {% include 'course/nav.html' %}
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        <form action="{% url 'course:dashboard' %}" method="get">
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Группа</label>
                        {% render_field filter.form.group class+="form-control"  %}
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Порядковый номер</label>
                        {% render_field filter.form.index_number class+="form-control"  %}
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Служба в Вооруженных силах</label>
                        {% render_field filter.form.military class+="form-control"  %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label>ФИО</label>
                        {% render_field filter.form.fio class+="form-control"  %}
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Поиск</button>&nbsp;&nbsp;<a href="{% url 'course:dashboard' %}" class="btn btn-primary">Сбросить фильтр</a>
        </form>
    </div>
    <br><br>

    <div class="container-fluid">
        <table class="table table-hover">
            <thead class="table-primary">
            <tr>
                <th scope="col">Группа</th>
                <th scope="col">ФИО</th>
                <th scope="col">Порядковый номер</th>
                <th scope="col">Национальность</th>
                <th scope="col">Вероисповедание</th>
                <th scope="col">Дата рождения</th>
                <th scope="col">Место рождения</th>
                <th scope="col">Образование</th>
                <th scope="col">Год окончания</th>
                <th scope="col">Специальность</th>
                <th scope="col">Служба в ВС</th>
                <th scope="col">Служба в ВС с:</th>
                <th scope="col">Служба в ВС по:</th>
                <th scope="col">Место службы</th>
                <th scope="col">Род войск</th>
                <th scope="col">Семейное положение</th>
                <th scope="col">Ранее в браке</th>
                <th scope="col">Состоял в браке с:</th>
                <th scope="col">Состоял в браке по:</th>
                <th scope="col">Имеются ли у Вас дети</th>
                <th scope="col">Пол и год рождения</th>
                <th scope="col">В дошкольном возрасте в вашем воспитании преимущественно принимали участие</th>
                <th scope="col">Иное</th>
                <th scope="col">Родители на момент поступления в Академию МВД</th>
                <th scope="col">Какие взаимоотношения преобладают между вашими родителями, лицами их заменяющими</th>
                <th scope="col">Братья и сестры</th>
                <th scope="col">Интересы, увлечения, хобби</th>
                <th scope="col">Интересы, увлечения, хобби (иное)</th>
                <th scope="col">За последние 2–3 года, каким видом спорта вы занимались на постоянной основе?</th>
                <th scope="col">Уровень занятий</th>
                <th scope="col">Периодичность</th>
                <th scope="col">Достижения</th>
                <th scope="col">На постоянной основе спортом</th>
                <th scope="col">Имеются ли хронические заболевания</th>
                <th scope="col">Если да, то какие</th>
                <th scope="col">Были ли у вас ранения, травмы, переломы, контузии</th>
                <th scope="col">Если да, то какие</th>
                <th scope="col">Особенности, которых вы стесняетесь</th>
                <th scope="col">Особенности, которых вы стесняетесь (иное)</th>
                <th scope="col">Родственники на учете</th>
                <th scope="col">Родственники на учете (иное)</th>
                <th scope="col">Материальная обеспеченность семьи</th>
                <th scope="col">Жилое помещение</th>
                <th scope="col">Жилое помещение (иное)</th>
                <th scope="col">Число жилых комнат</th>
                <th scope="col">Количество проживающих человек</th>
                <th scope="col">Имеется ли отдельная комната</th>
                <th scope="col">В какой деятельности Вы бы хотели реализовать себя</th>
                <th scope="col">В какой деятельности Вы бы хотели реализовать себя (иное)</th>
                <th scope="col">Какими способностями, Вы обладаете</th>
                <th scope="col">Какими способностями, Вы обладаете (иное)</th>
                <th scope="col">компьютерные / мобильные игры</th>
                <th scope="col">Количество постоянных друзей</th>
                <th scope="col">Мессенджеры</th>
                <th scope="col">Курение</th>
                <th scope="col">Если бы не поступил в Академия МВД</th>
            </tr>
            </thead>
            <tbody>
            {% for item in list %}
                <tr>
                    <td class="d-flex justify-content-center">{{ item.group }}</td>
                    <td>{{ item.fio }}</td>
                    <td>{{ item.index_number }}</td>
                    <td>{{ item.nationality }}</td>
                    <td>{{ item.religion }}</td>
                    <td>{{ item.date_of_birth }}</td>
                    <td>{{ item.birth_place }}</td>
                    <td>{{ item.get_education }}</td>
                    <td>{{ item.year_of_graduation }}</td>
                    <td>{{ item.specialty }}</td>
                    <td>{{ item.get_military }}</td>
                    <td>{{ item.military_year_since|default:"" }}</td>
                    <td>{{ item.military_year_till|default:"" }}</td>
                    <td>{{ item.military_place|default:"" }}</td>
                    <td>{{ item.type_of_army|default:"" }}</td>
                    <td>{{ item.get_family_status }}</td>
                    <td>{{ item.get_marriage }}</td>
                    <td>{{ item.marriage_year_since|default:"" }}</td>
                    <td>{{ item.marriage_year_till|default:"" }}</td>
                    <td>{{ item.get_children }}</td>
                    <td>{{ item.children_info|default:"" }}</td>
                    <td>
                        {%  for part in item.participation_in_education.all %}
                            {{ part.participation }}, <br>
                        {% endfor %}
                    <td>{{ item.participation_in_education_other|default:"" }}</td>
                    <td>{{ item.get_parents }}</td>
                    <td>
                        {%  for relationship in item.relationship.all %}
                            {{ relationship.relationship }}, <br>
                        {% endfor %}
                    </td>
                    <td>{{ item.siblings }}</td>
                    <td>
                        {%  for interest in item.interest.all %}
                            {{ interest.interest_name }}, <br>
                        {% endfor %}
                    </td>
                    <td>{{ item.interest_other|default:"" }}</td>
                    <td>{{ item.kind_of_sport|default:"" }}</td>
                    <td>{{ item.get_sport_level|default:"" }}</td>
                    <td>{{ item.get_sport_periodicity }}</td>
                    <td>{{ item.achievements }}</td>
                    <td>{{ item.get_not_prof }}</td>
                    <td>{{ item.get_is_chronic_diseases }}</td>
                    <td>{{ item.chronic_diseases|default:"" }}</td>
                    <td>{{ item.get_is_injury }}</td>
                    <td>{{ item.injury }}</td>
                    <td>
                        {%  for particular_qualities in item.particular_qualities.all %}
                            {{ particular_qualities.particular_qualities }}, <br>
                        {% endfor %}
                    </td>
                    <td>{{ item.particular_qualities_other }}</td>
                    <td>
                        {%  for relatives_record in item.relatives_record.all %}
                            {{ relatives_record.record }}, <br>
                        {% endfor %}
                    </td>
                    <td>{{ item.relatives_record_other }}</td>
                    <td>{{ item.get_level_of_wealth }}</td>
                    <td>{{ item.get_living_conditions_premises }}</td>
                    <td>{{ item.get_living_conditions_premises_other }}</td>
                    <td>{{ item.get_living_conditions_room_count }}</td>
                    <td>{{ item.get_living_conditions_people_count }}</td>
                    <td>{{ item.get_is_own_room }}</td>
                    <td>
                        {%  for activity in item.activity.all %}
                            {{ activity.activity }}, <br>
                        {% endfor %}
                    </td>
                    <td>{{ item.activity_other }}</td>
                    <td>
                        {%  for ability in item.ability.all %}
                            {{ ability.ability }}, <br>
                        {% endfor %}
                    </td>
                    <td>{{ item.ability_other }}</td>
                    <td>{{ item.get_gaming }}</td>
                    <td>{{ item.friends_count }}</td>
                    <td>
                        {%  for messenger in item.messenger.all %}
                            {{ messenger.messenger }}, <br>
                        {% endfor %}
                    </td>
                    <td>{{ item.get_smoking }}</td>
                    <td>{{ item.if_had_not_entered }}</td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>





{% endblock %}

AMIAQuestioning/course/templates/course/input_form.html
{% extends "base.html" %}

{% block title %}
    <title>Анкета</title>
    {% load widget_tweaks %}
    {% load static %}
    <style type="text/css">
        ul {
            list-style-type: none;
        }
    </style>
{% endblock %}

{% block nav %}
    <div class="container-fluid">
        {% include 'course/nav.html' %}
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% include 'course/input_blocks/errors.html' %}
        <form class="needs-validation" action="{% url 'course:add' %}" method="post" novalidate>{% csrf_token %}
            <div class="jumbotron">

                <div class="form-group row">
                    <label class="col-md-6 col-form-label"><b>АНКЕТА ПЕРВОКУРСНИКА</b></label>
                    {#                    <div class="col-md-6">#}
                    {#                        {% render_field form.group class+="form-control" style="width: 300px;" %}#}
                    {#                    </div>#}
                </div>

                <div class="form-group">
                    <label><b>Учебная группа</b></label>
                    {% render_field form.group class+="form-control" style="width: 300px;" %}
                </div>


                {% include 'course/input_blocks/personal_info.html' %}
                <br>
                <div class="divider_main"></div>
                {% include 'course/input_blocks/education.html' %}
                <br>
                <div class="divider_main"></div>
                {% include 'course/input_blocks/army.html' %}
                <br>
                <div class="divider_main"></div>
                <br>
                {% include 'course/input_blocks/children.html' %}
                <br>
                <div class="divider_main"></div>
                <br>
                {% include 'course/input_blocks/family.html' %}
                <div class="divider_main"></div>
                <br>
                {% include 'course/input_blocks/interest.html' %}
                <br>
                <div class="divider_main"></div>
                <br>
                {% include 'course/input_blocks/diseases.html' %}
                <br>
                <div class="divider_main"></div>
                <br>
                {% include 'course/input_blocks/qualities.html' %}
                <br>
                <div class="divider_main"></div>
                <br>
                {% include 'course/input_blocks/activity.html' %}
            </div>
            <button type="submit" class="btn btn-primary">Отправить анкету!</button>
            <br><br>
        </form>

        <div class="alert alert-warning" role="alert">
            Конфиденциально. Информация защищена в соответствии с законом Республики Беларусь
            от 1 июля 2010 г. № 153-З «Об оказании психологической помощи»
            Заполненный бланк сдавать только психологу.
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'course/js/main.js' %}"></script>
{#    <script>#}
{#        $("#id_fio").blur(function () {#}
{#            window.fio = $(this).val();#}
{#        }); #}
{#        $("#id_group").blur(function () {#}
{#            window.group = $(this).val();#}
{#        });#}
{#    </script>#}
{% endblock %}

AMIAQuestioning/course/templates/course/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/"><img src="{% static 'questioning/img/favicon.ico' %}" width="30" height="30"
                                          class="d-inline-block align-top" alt="" loading="lazy">&nbsp;Академия МВД</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="">Вы вошли в систему как
                        - {{ request.user.last_name }} {{ request.user.first_name }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Прохождение тестов</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="\admin">Администрирование</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'personalwork:work_list' %}">Индивидуальная работа</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Выход из системы</a>
                </li>
            {% else %}
                <a class="nav-link" href="{% url 'login' %}">Вход в систему</a>
            {% endif %}
        </ul>
    </div>
</nav>

AMIAQuestioning/course/templates/course/success.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>Анкета</title>
{% endblock %}

{% block nav %}{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="jumbotron">
            <h1 class="display-4">Отлично! Ваши результаты приняты!</h1>
            <h4>Ожидайте следующего задания!</h4>
            <hr class="my-4">
        </div>
    </div>
    <br>
    <h1 id="user_countdown" class="text-center"></h1>
{% endblock %}

{% block js %}
    <script src="{% static 'big_test/js/countdown.js' %}"></script>
{% endblock %}