AMIAQuestioning/AMIAQuestioning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('questioning/', include('questioning.urls')),
    path('course/', include('course.urls')),
    path('graduate/', include('graduate.urls')),
    path('big_test/', include('big_test.urls')),
    path('adaptation/', include('adaptation.urls')),
    path('beka/', include('beka_scale.urls')),
    path('personal-work/', include('personalwork.urls')),
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
    # path('', RedirectView.as_view(url='/questioning'), name='index'),
    # path('results/', TemplateView.as_view(template_name="index.html"), name='results'),
    path('accounts/', include('django.contrib.auth.urls'))
]

AMIAQuestioning/adaptation/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'adaptation'

urlpatterns = [
    path('', views.adaptation_add, name='adaptation_add'),
    path('success', views.success, name='adaptation_success'),
    path('dashboard/', login_required(views.dashboard), name='dashboard'),
]

AMIAQuestioning/beka_scale/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'beka_scale'

urlpatterns = [
    path('', views.test_form_add, name='test_add'),
    path('dashboard', login_required(views.dashboard), name='test_dashboard'),
    path('success', views.success, name='test_success'),
]

AMIAQuestioning/big_test/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'testing'

urlpatterns = [
    path('', views.test_form_add, name='test_add'),
    path('dashboard', login_required(views.dashboard), name='test_dashboard'),
    path('success', views.success, name='test_success'),
]

AMIAQuestioning/course/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'course'

urlpatterns = [
    path('', views.questioning_add, name='add'),
    path('success/', views.success, name='success'),
    path('dashboard/', login_required(views.dashboard), name='dashboard'),
]

AMIAQuestioning/graduate/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'graduate'

urlpatterns = [
    path('', views.graduate_add, name='add'),
    path('success/', views.success, name='success'),
    path('dashboard/', login_required(views.dashboard), name='dashboard'),
]

AMIAQuestioning/templates/base.html
<!doctype html>
<html lang="ru">
<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'questioning/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'questioning/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'questioning/css/bootstrap-grid.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'questioning/css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'questioning/css/select2.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'course/css/main.css' %}">

    {% block title %}{% endblock %}
    <link rel="shortcut icon" href="{% static 'questioning/img/favicon.ico' %}"/>
</head>
<body>

{% block nav %}

{% endblock %}
{% block content %}{% endblock %}

<!-- Optional JavaScript -->
<script src="{% static 'questioning/js/JQueryLocal.js' %}"></script>
{#<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>#}

<script src="{% static 'questioning/js/bootstrap.js' %}"></script>
<script src="{% static 'questioning/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'questioning/js/select2.js' %}"></script>

{#<script src="{% static 'course/js/main.js' %}"></script>#}
<script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
        'use strict';
        window.addEventListener('load', function () {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('submit', function (event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>

<script>
    $(document).ready(function () {
        $('.my-select2').select2();
    });
</script>

{% block js %}{% endblock %}
</body>
</html>

AMIAQuestioning/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>Home</title>{% endblock %}

{% block nav %}{% include 'course/nav.html' %}{% endblock %}

{% block content %}
    <style>
        @media (max-width: 767.98px) {
            .offcanvas-collapse {
                position: fixed;
                top: 56px; /* Height of navbar */
                bottom: 0;
                width: 100%;
                padding-right: 1rem;
                padding-left: 1rem;
                overflow-y: auto;
                background-color: var(--gray-dark);
                transition: -webkit-transform .3s ease-in-out;
                transition: transform .3s ease-in-out;
                transition: transform .3s ease-in-out, -webkit-transform .3s ease-in-out;
                -webkit-transform: translateX(100%);
                transform: translateX(100%);
            }

            .offcanvas-collapse.open {
                -webkit-transform: translateX(-1rem);
                transform: translateX(-1rem); /* Account for horizontal padding on navbar */
            }
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            -ms-flex-wrap: nowrap;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            color: rgba(255, 255, 255, .75);
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .nav-underline .nav-link {
            padding-top: .75rem;
            padding-bottom: .75rem;
            font-size: .875rem;
            color: var(--secondary);
        }

        .nav-underline .nav-link:hover {
            color: var(--blue);
        }

        .nav-underline .active {
            font-weight: 500;
            color: var(--gray-dark);
        }

        .text-white-50 {
            color: rgba(255, 255, 255, .5);
        }

        .bg-purple {
            background-color: var(--purple);
        }

        .border-bottom {
            border-bottom: 1px solid #e5e5e5;
        }

        .box-shadow {
            box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05);
        }

        .lh-100 {
            line-height: 1;
        }

        .lh-125 {
            line-height: 1.25;
        }

        .lh-150 {
            line-height: 1.5;
        }
    </style>

    <br>
    <main role="main" class="container">
        <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded box-shadow">
            <img class="mr-3" src="{% static 'questioning/img/favicon.ico' %}" alt="" width="48" height="48">
            <div class="lh-100">
                <h6 class="mb-0 text-white lh-100">Отдел психологического сопровождения</h6>
            </div>
        </div>


        <div class="my-3 p-3 bg-white rounded box-shadow">
            <h6 class="border-bottom border-gray pb-2 mb-0">Анкеты и тесты для прохождения</h6>
            <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <div>
                            <strong class="text-gray-dark">Анонимная анкета</strong>
                            <span class="d-block pt-2">Анонимная анкета изучения предпочтений профессионального выбора абитуриента</span>
                        </div>
                        <div>
                            <a href="{% url 'questioning:add' %}" class="btn btn-outline-primary"
                               style="min-width: 114px;">
                                <nobr>Пройти тест</nobr>
                            </a>
                            {% if user.is_authenticated %}
                                <a href="{% url 'questioning:dashboard-pre' %}" class="btn btn-outline-primary">Смотреть
                                    результаты</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <div>
                            <strong class="text-gray-dark">Анкета первокурсника</strong>
                            <span class="d-block mt-2">Анкета первокурсника</span>
                        </div>
                        <div>
                            <a href="{% url 'course:add' %}" class="btn btn-outline-primary" style="min-width: 114px;">
                                <nobr>Пройти тест</nobr>
                            </a>
                            {% if user.is_authenticated %}
                                <a href="{% url 'course:dashboard' %}" class="btn btn-outline-primary">Смотреть
                                    результаты</a>
                            {% endif %}
                        </div>
                    </div>

                </div>
            </div>
            <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <div>
                            <strong class="text-gray-dark">Анкета выпускника</strong>
                            <span class="d-block mt-2">Анкета выпускника</span>
                        </div>
                        <div>
                            <a href="{% url 'graduate:add' %}" class="btn btn-outline-primary"
                               style="min-width: 114px;">
                                <nobr>Пройти тест</nobr>
                            </a>
                            {% if user.is_authenticated %}
                                <a href="{% url 'graduate:dashboard' %}" class="btn btn-outline-primary">Смотреть
                                    результаты</a>
                            {% endif %}
                        </div>
                    </div>

                </div>
            </div>
            <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <div>
                            <strong class="text-gray-dark">Тест оценки психологической устойчивости</strong>
                            <span class="d-block mt-2">Опросник (60 утверждений)</span>
                        </div>

                        <div>
                            <a href="{% url 'testing:test_add' %}" class="btn btn-outline-primary"
                               style="min-width: 114px;">
                                <nobr>Пройти тест</nobr>
                            </a>
                            {% if user.is_authenticated %}
                                <a href="{% url 'testing:test_dashboard' %}" class="btn btn-outline-primary">Смотреть
                                    результаты</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <div>
                            <strong class="text-gray-dark">Анкета адаптации</strong>
                            <span class="d-block mt-2">Оценка адаптации к условиям обучения в Академии МВД</span>
                        </div>

                        <div>
                            <a href="{% url 'adaptation:adaptation_add' %}" class="btn btn-outline-primary"
                               style="min-width: 114px;">
                                <nobr>Пройти тест</nobr>
                            </a>
                            {% if user.is_authenticated %}
                                <a href="{% url 'adaptation:dashboard' %}" class="btn btn-outline-primary">Смотреть
                                    результаты</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <div>
                            <strong class="text-gray-dark">Шкала Бека(BHI)</strong>
                            <span class="d-block mt-2">Опросник (20 утверждений)</span>
                        </div>
                        <div>
                            <a href="{% url 'beka_scale:test_add' %}" class="btn btn-outline-primary"
                               style="min-width: 114px;">
                                <nobr>Пройти тест</nobr>
                            </a>
                            {% if user.is_authenticated %}
                                <a href="{% url 'beka_scale:test_dashboard' %}" class="btn btn-outline-primary">Смотреть
                                    результаты</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

AMIAQuestioning/templates/result.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>Home</title>{% endblock %}

{% block nav %}{% include 'course/nav.html' %}{% endblock %}

{% block content %}
    <style>
        @media (max-width: 767.98px) {
            .offcanvas-collapse {
                position: fixed;
                top: 56px; /* Height of navbar */
                bottom: 0;
                width: 100%;
                padding-right: 1rem;
                padding-left: 1rem;
                overflow-y: auto;
                background-color: var(--gray-dark);
                transition: -webkit-transform .3s ease-in-out;
                transition: transform .3s ease-in-out;
                transition: transform .3s ease-in-out, -webkit-transform .3s ease-in-out;
                -webkit-transform: translateX(100%);
                transform: translateX(100%);
            }
            .offcanvas-collapse.open {
                -webkit-transform: translateX(-1rem);
                transform: translateX(-1rem); /* Account for horizontal padding on navbar */
            }
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            -ms-flex-wrap: nowrap;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            color: rgba(255, 255, 255, .75);
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .nav-underline .nav-link {
            padding-top: .75rem;
            padding-bottom: .75rem;
            font-size: .875rem;
            color: var(--secondary);
        }

        .nav-underline .nav-link:hover {
            color: var(--blue);
        }

        .nav-underline .active {
            font-weight: 500;
            color: var(--gray-dark);
        }

        .text-white-50 { color: rgba(255, 255, 255, .5); }

        .bg-purple { background-color: var(--purple); }

        .border-bottom { border-bottom: 1px solid #e5e5e5; }

        .box-shadow { box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05); }

        .lh-100 { line-height: 1; }
        .lh-125 { line-height: 1.25; }
        .lh-150 { line-height: 1.5; }
    </style>

<br>
    <main role="main" class="container">
        <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded box-shadow">
            <img class="mr-3" src="{% static 'questioning/img/favicon.ico' %}" alt="" width="48" height="48">
            <div class="lh-100">
                <h6 class="mb-0 text-white lh-100">Отдел психологического сопровождения</h6>
{#                <small>Since 2011</small>#}
            </div>
        </div>


        <div class="my-3 p-3 bg-white rounded box-shadow">
            <h6 class="border-bottom border-gray pb-2 mb-0">Результаты анкетирования</h6>
            <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <strong class="text-gray-dark">Анонимная анкета</strong>
                        <a href="{% url 'questioning:dashboard' %}" class="btn btn-primary">Смотреть результаты</a>
                    </div>
                    <span class="d-block">Анонимная анкета изучения предпочтений профессионального выбора абитуриента</span>
                </div>
            </div>
            <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <strong class="text-gray-dark">Анкета первокурсника</strong>
                        <a href="{% url 'course:dashboard' %}" class="btn btn-primary">Смотреть результаты</a>
                    </div>
                    <span class="d-block">Анкета первокурсника</span>
                </div>
            </div>
            <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <strong class="text-gray-dark">Анкета выпускника</strong>
                        <a href="{% url 'graduate:dashboard' %}" class="btn btn-primary">Смотреть результаты</a>
                    </div>
                    <span class="d-block">Анкета выпускника</span>
                </div>
            </div>
            <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <strong class="text-gray-dark">Тест оценки психологической устойчивости</strong>
                        <a href="{% url 'testing:test_dashboard' %}" class="btn btn-primary">Смотреть результаты</a>
                    </div>
                    <span class="d-block">Тест из 60 вопросов</span>
                </div>
            </div>
            <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <strong class="text-gray-dark">Тест № 5</strong>
                        <a href="#" class="btn btn-primary">Смотреть результаты</a>
                    </div>
                    <span class="d-block">Описание теста</span>
                </div>
            </div>
        </div>
    </main>

{% endblock %}