AMIAQuestioning/AMIAQuestioning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('questioning/', include('questioning.urls')),
    path('course/', include('course.urls')),
    path('graduate/', include('graduate.urls')),
    path('big_test/', include('big_test.urls')),
    path('adaptation/', include('adaptation.urls')),
    path('beka/', include('beka_scale.urls')),
    path('personal-work/', include('personalwork.urls')),
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
    # path('', RedirectView.as_view(url='/questioning'), name='index'),
    # path('results/', TemplateView.as_view(template_name="index.html"), name='results'),
    path('accounts/', include('django.contrib.auth.urls'))
]

AMIAQuestioning/course/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'course'

urlpatterns = [
    path('', views.questioning_add, name='add'),
    path('success/', views.success, name='success'),
    path('dashboard/', login_required(views.dashboard), name='dashboard'),
]

AMIAQuestioning/personalwork/urls.py
from django.urls import path
from . import views


app_name = 'personalwork'

urlpatterns = [
    path('', views.work_list, name='work_list'),
    path('add', views.work_input, name='work_input'),
    path('<work_id>/update', views.work_update, name='work_update'),
    # path('subdivisions', views.get_subdivisions, name='work_update'),
]

AMIAQuestioning/personalwork/models.py
from django.db import models
from django.contrib.auth.models import User


class Rank(models.Model):
    rank_title = models.CharField(max_length=255, verbose_name="Звание")

    def __str__(self):
        return self.rank_title

    class Meta:
        ordering = ('rank_title',)
        verbose_name = 'Звание'
        verbose_name_plural = 'Звания'


class Subdivision(models.Model):
    subdivision_title = models.CharField(max_length=255, verbose_name="Подразделение")

    def __str__(self):
        return self.subdivision_title

    class Meta:
        ordering = ('subdivision_title',)
        verbose_name = 'Подразделение'
        verbose_name_plural = 'Подразделения'


class WorkKind(models.Model):
    work_kind = models.CharField(max_length=255, verbose_name="Вид работы")

    def __str__(self):
        return self.work_kind

    class Meta:
        ordering = ('work_kind',)
        verbose_name = 'Вид работы'
        verbose_name_plural = 'Виды работы'


class Request(models.Model):
    work_request = models.CharField(max_length=255, verbose_name="Запрос")

    def __str__(self):
        return self.work_request

    class Meta:
        ordering = ('work_request',)
        verbose_name = 'Запрос'
        verbose_name_plural = 'Запросы'


class WorkDone(models.Model):
    work_done = models.CharField(max_length=255, verbose_name="Основание и проведенная работа")

    def __str__(self):
        return self.work_done

    class Meta:
        ordering = ('work_done',)
        verbose_name = 'Основание и проведенная работа'
        verbose_name_plural = 'Основания и проведенные работы'


class PersonalWork(models.Model):
    lastname = models.CharField(max_length=255, verbose_name="Фамилия и инициалы")
    work_date = models.DateField(verbose_name="Дата")
    rank = models.ForeignKey(Rank, on_delete=models.SET_NULL, verbose_name="Звание", blank=True, null=True)
    subdivision = models.ForeignKey(Subdivision, verbose_name="Подразделение", on_delete=models.CASCADE)
    work_kind = models.ForeignKey(WorkKind, verbose_name="Вид работы", on_delete=models.CASCADE)
    work_request = models.ForeignKey(Request, verbose_name="Запрос", on_delete=models.CASCADE)
    work_done = models.ForeignKey(WorkDone, verbose_name="Основание и проведеннная работа", on_delete=models.CASCADE)
    conclusion = models.TextField(verbose_name="Выводы", blank=True, null=True)
    recommendations = models.TextField(verbose_name="Рекомендации", blank=True, null=True)
    executor = models.ForeignKey(User, verbose_name="Исполнитель", on_delete=models.CASCADE)
    add_date_time = models.DateTimeField(verbose_name="Дата и время добавления записи", auto_now_add=True)
    last_modification = models.DateTimeField(verbose_name="Дата и время последнего редактирования", auto_now=True)
    extra_data = models.TextField(verbose_name="Дополнительная информация", blank=True, null=True)

    def __str__(self):
        return self.lastname + ' исполнитель - ' + str(self.executor)

    class Meta:
        ordering = ('-work_date', '-id')
        verbose_name = 'Индивидуальная работа'
        verbose_name_plural = 'Индивидуальные работы'

AMIAQuestioning/personalwork/forms.py
from django.forms import ModelForm
from .models import PersonalWork
from django import forms

myDateInput = forms.DateInput(format=('%Y-%m-%d'), attrs={'type': 'date'})


class PersonalWorkForm(ModelForm):
    class Meta:
        model = PersonalWork
        fields = ['lastname', 'work_date', 'rank', 'subdivision', 'work_kind', 'work_request', 'work_done',
                  'conclusion', 'recommendations', 'extra_data']
        widgets = {'work_date': myDateInput}

AMIAQuestioning/personalwork/views.py
from django.shortcuts import render
from datetime import datetime
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .filters import PersonalWorkFilter
from .models import PersonalWork, Subdivision
from .forms import PersonalWorkForm


@login_required
def work_list(request):
    path = str(request.get_full_path())
    request.session['next_path'] = path
    if request.user.is_superuser:
        works_list = PersonalWork.objects.all()
    else:
        works_list = PersonalWork.objects.filter(executor=request.user)
    f = PersonalWorkFilter(request.GET, queryset=works_list)
    return render(request, 'personalwork/work_list.html',
                  {'works_list': f.qs,
                   'filter': f
                   })


@login_required
def work_input(request):
    if request.method == 'POST':
        form = PersonalWorkForm(request.POST)
        if form.is_valid():
            work = form.save(commit=False)
            work.executor = request.user
            work.save()
            if 'next_path' in request.session:
                return HttpResponseRedirect(request.session.get('next_path'))
            else:
                return HttpResponseRedirect(reverse('personalwork:work_list'))
    else:
        form = PersonalWorkForm(initial={'work_date': datetime.now()})
        return render(request, 'personalwork/work_input_form.html', {'form': form})


@login_required
def work_update(request, work_id):
    if request.method == 'POST':
        obj = get_object_or_404(PersonalWork, pk=work_id)
        form = PersonalWorkForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            if 'next_path' in request.session:
                return HttpResponseRedirect(request.session.get('next_path'))
            else:
                return HttpResponseRedirect(reverse('personalwork:work_list'))
        else:
            return render(request, 'personalwork/work_update_form.html', {'form': form, 'work': obj})
    else:
        work = get_object_or_404(PersonalWork, pk=work_id)
        form = PersonalWorkForm(instance=work)
    return render(request, 'personalwork/work_update_form.html', {'form': form, 'work': work})


# def get_subdivisions(request):
#     import requests
#     r = requests.get('http://192.168.0.124/api/subdivisions/')
#     items = r.json()
#
#     for item in items:
#         subdivision = Subdivision(subdivision_title=item['subdivision_name'])
#         subdivision.save()
#
#     return JsonResponse({'old': 'success'}, safe=False)

AMIAQuestioning/personalwork/templates/personalwork/work_input_form.html
{% extends "base.html" %}

{% block title %}
    <title>Новая запись</title>
    {% load widget_tweaks %}
    {% load static %}
{% endblock %}

{% block nav %}
    <div class="container-fluid">
        {% include 'course/nav.html' %}
    </div>
{% endblock %}

{% block content %}
    <div class="container shadow-lg p-3 mb-5 bg-white rounded">
        {% for error in form.non_field_errors %}
            <b>{{ field.label }} {{ error }}</b><br>
        {% endfor %}

        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}
                    <b>{{ field.label }} {{ error }}</b><br>
                {% endfor %}
            {% endif %}
        {% endfor %}
        <div class="mt-2"></div>
        {% block form_title %}
            <form class="needs-validation" action="{% url 'personalwork:work_input' %}" method="POST" novalidate>
            {% csrf_token %}
        {% endblock %}

        <div class="row">
            <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">Дата</label>
                    {% render_field form.work_date class+="form-control" %}
                    <div class="invalid-feedback">
                        Обязательное поле
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">Фамилия</label>
                    {% render_field form.lastname class+="form-control" %}
                    <div class="invalid-feedback">
                        Обязательное поле
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">Звание</label>
                    {% render_field form.rank class+="form-control" %}
                </div>
            </div>
            <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">Подразделение</label>
                    {% render_field form.subdivision class+="form-control" %}
                    <div class="invalid-feedback">
                        Обязательное поле
                    </div>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">Вид работы</label>
                    {% render_field form.work_kind class+="form-control" %}
                    <div class="invalid-feedback">
                        Обязательное поле
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">Запрос</label>
                    {% render_field form.work_request class+="form-control" %}
                    <div class="invalid-feedback">
                        Обязательное поле
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="mb-3">
                    <label class="form-label">Основание и проведенная работа</label>
                    {% render_field form.work_done class+="form-control" %}
                    <div class="invalid-feedback">
                        Обязательное поле
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label">Выводы</label>
                    {% render_field form.conclusion class+="form-control" rows="2" %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label">Рекомендации</label>
                    {% render_field form.recommendations class+="form-control" rows="2" %}
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
{% endblock %}

AMIAQuestioning/personalwork/templates/personalwork/work_list.html
{% extends "base.html" %}

{% block title %}
    <title>Индивидуальные работы</title>
    {% load widget_tweaks %}
    {% load static %}
{% endblock %}

{% block nav %}
    <div class="container-fluid">
        {% include 'course/nav.html' %}
    </div>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="mt-4"></div>
        {% if request.user.is_superuser %}
            <div class="container shadow-lg p-3 mb-5 bg-white rounded">
                <form action="{% url 'personalwork:work_list' %}" method="GET">
                    <div class="row">
                        <div class="col-md-4">
                            <label class="form-label">Фамилия</label>
                            {% render_field filter.form.lastname class+="form-control" style="width: 100%" %}
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Группа</label>
                            {% render_field filter.form.subdivision class+="form-control my-select2" style="width: 100%" %}
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Звание</label>
                            {% render_field filter.form.rank class+="form-control my-select2" style="width: 100%" %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label class="form-label">Дата с</label>
                            {% render_field filter.form.work_date_start class+="form-control" style="width: 100%" %}
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Дата по</label>
                            {% render_field filter.form.work_date_end class+="form-control" style="width: 100%" %}
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Вид работы</label>
                            {% render_field filter.form.work_kind class+="form-control my-select2" style="width: 100%" %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label class="form-label">Запрос</label>
                            {% render_field filter.form.work_request class+="form-control my-select2" style="width: 100%" %}
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Проведенная работа</label>
                            {% render_field filter.form.work_done class+="form-control my-select2" style="width: 100%" %}
                        </div>
                        <div class="col-md-4">
                            <label class="form-label">Исполнитель</label>
                            {% render_field filter.form.executor class+="form-control my-select2" style="width: 100%" %}
                        </div>
                    </div>
                    <button class="btn btn-primary mt-3" type="submit">Поиск</button>
                    <a class="btn btn-primary mt-3" href="{% url 'personalwork:work_list' %}">Сбросить фильтр</a>
                </form>
            </div>
        {% endif %}
        <div class="d-flex justify-content-end my-3">
            <a class="btn btn-primary" href="{% url 'personalwork:work_input' %}">Новая запись</a>
        </div>

        {% if works_list %}
            <h5 class="my-3">Всего записей - {{ works_list.count }}</h5>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col" class="table-primary align-middle text-center">№ п.п</th>
                    <th scope="col" class="table-primary align-middle text-center">Дата</th>
                    <th scope="col" class="table-primary align-middle text-center">Звание</th>
                    <th scope="col" class="table-primary align-middle text-center">Фамилия и инициалы</th>
                    <th scope="col" class="table-primary align-middle text-center">Подразделение</th>
                    <th scope="col" class="table-primary align-middle text-center">Вид работы</th>
                    <th scope="col" class="table-primary align-middle text-center">Запрос</th>
                    <th scope="col" class="table-primary align-middle text-center">Основание и проведенная работа</th>
                    <th scope="col" class="table-primary align-middle text-center">Выводы</th>
                    <th scope="col" class="table-primary align-middle text-center">Рекомендации</th>
                    {% if request.user.is_superuser %}
                        <th scope="col" class="table-primary align-middle text-center">Исполнитель</th>
                        <th scope="col" class="table-primary align-middle text-center">Дата создания записи</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for work in works_list %}
                    <tr>
                        <td class="align-middle text-center">{{ forloop.counter }}</td>
                        <td class="align-middle text-center">{{ work.work_date|date:"d.m.Y" }}</td>
                        <td class="align-middle text-center">{{ work.rank }}</td>
                        <td class="align-middle text-center">
                            <nobr><a class="link-secondary"
                                     href="{% url 'personalwork:work_update' work.id %}">{{ work.lastname }}</a></nobr>
                        </td>
                        <td class="align-middle text-center">{{ work.subdivision }}</td>
                        <td class="align-middle text-center">{{ work.work_kind }}</td>
                        <td class="align-middle text-center">{{ work.work_request }}</td>
                        <td class="align-middle text-center">{{ work.work_done }}</td>
                        <td class="align-middle text-center">{{ work.conclusion }}</td>
                        <td class="align-middle text-center">{{ work.recommendations }}</td>
                        {% if request.user.is_superuser %}
                            <td class="align-middle text-center">{{ work.executor.last_name }} {{ work.executor.first_name }}</td>
                            <td class="align-middle text-center">{{ work.add_date_time|date:"d.m.Y H:m" }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="container">
                <h5>Список пуст!</h5>
            </div>
        {% endif %}
    </div>
{% endblock %}

AMIAQuestioning/personalwork/templates/personalwork/work_update_form.html
{% extends 'personalwork/work_input_form.html' %}

{% block title %}
    <title>{{ work.lastname }} - редактирование</title>
{% endblock %}

{% block form_title %}
    <form class="needs-validation" action="{% url 'personalwork:work_update'  work_id=work.id %}" method="POST"
          novalidate>{% csrf_token %}
{% endblock %}